import Footer from "./Components/Footer";
import Header from "./Components/Header";

export const metadata = {
  title: "Home page | Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}